trigger:
- main

pool:
  name: Default

steps:
- checkout: self

- script: |
    echo "Current directory:"
    pwd
    echo "Listing repo files:"
    ls -la

    echo "Cleaning NGINX folder..."
    sudo rm -rf /var/www/html/*

    echo "Copying full project..."
    sudo cp -r $(Build.SourcesDirectory)/* /var/www/html/

    echo "Restarting NGINX..."
    sudo systemctl restart nginx

  displayName: Deploy Full Project to NGINX